name: Draft PDF
on:
  push:
    branches: [ main ] 
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
  workflow_dispatch:

permissions:
  contents: write              # needed to commit the PDF

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper/paper.pdf
      - name: Commit PDF to repo (main only)
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'paper/paper.pdf'
          message: '(auto) Paper PDF Draft [skip ci]'
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'