name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with dev
    - name: Run flake8
      run: |
        make flake8
    - name: Run isort
      run: |
        make isort
    - name: Run black
      run: |
        make black