name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (for matrix generation)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate SciPy matrix
        id: gen
        run: |
          make scipymatrix
          echo "Generated:"
          cat matrix.json

      - name: Expose matrix as output
        id: out
        shell: bash
        run: |
          echo "matrix=$(cat matrix.json)" >> "$GITHUB_OUTPUT"

  build:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies (Poetry) and pin SciPy ${{ matrix.scipy }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry env use ${{ matrix.python }}
          poetry install --with dev
          poetry run pip install "scipy==${{ matrix.scipy }}"

      - name: Test
        run: |
          poetry run make pytest
